### ISSUE TITLE
wrong parameter sent to net.createConnection

### ISSUE THREAD

**Issue by sicavz** [rentzsch/portbridge.js#1]
Instead of 

``` javascript
net.createConnection(parseInt(parseInt)...
```

it should be

``` javascript
net.createConnection(parseInt(remotePort)...
```

otherwise you get this error

> net.js:917
>       throw new RangeError('port should be >= 0 and < 65536: ' +
>             ^
> RangeError: port should be >= 0 and < 65536: NaN
>     at Socket.connect (net.js:917:13)
>     at Object.exports.connect.exports.createConnection (net.js:92:35)
>     at Server.<anonymous> (d:\scripts\node.js\portbridge.js:22:36)
>     at Server.emit (events.js:107:17)
>     at TCP.onconnection (net.js:1330:8)

**Comment by rentzsch** [comment]
That's what I get for copying and pasting from another file instead of Doing The Right thing. Fixed, thanks.
